# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-12 06:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_auto_20210212_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='goal',
        ),
    ]
